package by.epam.finalTask.controller.command;

public enum  CommandName {
    SIGN_IN,
    REGISTRATION,
    REGISTRATION_PAGE,
    SIGN_IN_PAGE,
    MAIN_PAGE,
    ALBUMS_PAGE,
    PLAYLISTS_PAGE,
    USER_TRACKS,
    ALBUM_INFO,
    USER_ALBUMS,
    PLAYLIST_INFO,
    USER_PLAYLISTS,
    USER_WALLET,
    ADD_USER_WALLET,
    USER_PROFILE,
    UPDATE_USERNAME,
    UPDATE_PASSWORD,
    SIGN_OUT,
    ADD_COMMENT
}
